#!/usr/bin/env python3
# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Visual validation: triangulation covariance vs Monte Carlo.

Produces a small report of figures that show the analytical Sigma_X computed
by `compute_triangulation_covariance` agrees with Monte Carlo statistics
generated by perturbing camera intrinsics around their nominal values and
re-triangulating with the nominal K.

Plots written under tests/mc_plots/intrinsic_cov/:
  1. cov_projections.png    — XY/XZ/YZ MC scatter with analytic 1σ/2σ/3σ ellipses
  2. marginal_histograms.png — per-axis MC histograms with analytic Gaussian PDF
  3. nees_chi2.png          — Mahalanobis² histogram vs chi²(3) reference
  4. zoom_sweep.png         — trace(Σ_X) analytic vs MC across zoom commands
  5. matrix_compare.png     — matrix heatmap of empirical vs analytic Σ_X
"""

import argparse
import os

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(description="Plot MC vs analytical triangulation covariance")
AppLauncher.add_app_launcher_args(parser)
parser.set_defaults(headless=True)
parser.add_argument("--n-samples", type=int, default=10000)
parser.add_argument("--zoom-cmd", type=float, default=4.0,
                    help="Operator zoom command for the headline scenario (1..5)")
parser.add_argument("--target-distance", type=float, default=80.0)
parser.add_argument("--zoom-sweep", type=str, default="1.0,2.0,3.0,4.0,5.0",
                    help="Comma-separated zoom commands for the trace sweep panel")
parser.add_argument("--save-dir", type=str, default=None)
parser.add_argument("--seed", type=int, default=0)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import math
import sys
import numpy as np
import torch

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse

try:
    from scipy.stats import chi2 as chi2_dist
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False

from isaaclab_tasks.direct.iris_ma6.triangulation import (
    TriangulationCfg,
    compute_triangulation_covariance,
    compute_sigma_K_from_zoom,
    get_ray_directions_from_bbox,
    triangulate_targets,
)
from isaaclab_tasks.direct.iris_ma6.triangulation.triangulation import build_camera_transforms


def yaw_quat(yaw: float, device: torch.device) -> torch.Tensor:
    return torch.tensor(
        [math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2)],
        device=device, dtype=torch.float32,
    )


def build_scenario(target_distance: float, device: torch.device):
    """Three cameras on a circle around the target. Returns nominal pose tensors."""
    radius = target_distance
    altitude = 5.0
    angles_deg = [0.0, 60.0, 120.0]
    cam_xyz, cam_yaws = [], []
    for ang_deg in angles_deg:
        ang = math.radians(ang_deg)
        cam_xyz.append([radius * math.cos(ang), radius * math.sin(ang), altitude])
        cam_yaws.append(math.atan2(-math.sin(ang), -math.cos(ang)))
    cam_pos = torch.tensor(cam_xyz, device=device, dtype=torch.float32)
    cam_quat = torch.stack([yaw_quat(y, device) for y in cam_yaws], dim=0)
    target = torch.tensor([0.0, 0.0, altitude], device=device, dtype=torch.float32)
    return cam_pos, cam_quat, target


def project_through_intrinsics(X_w, cam_pos, R_wc, K):
    X_rel = X_w.view(1, 1, 3) - cam_pos
    Xc = torch.matmul(R_wc.transpose(-1, -2), X_rel.unsqueeze(-1)).squeeze(-1)
    Z = Xc[..., 2].clamp(min=1e-6)
    fx = K[..., 0, 0]; fy = K[..., 1, 1]
    cx = K[..., 0, 2]; cy = K[..., 1, 2]
    u = fx * (Xc[..., 0] / Z) + cx
    v = fy * (Xc[..., 1] / Z) + cy
    return torch.stack([u, v], dim=-1), Xc[..., 2]


def run_mc(zoom_cmd_value: float, target_distance: float, n_samples: int, device: torch.device):
    """Run MC for a single zoom level. Returns triangulated samples [V, 3], analytic Σ_X [3, 3], target."""
    C = 3
    cam_pos_nom, cam_quat_nom, X_target = build_scenario(target_distance, device)
    gimbal_zero = torch.zeros(1, C, device=device)

    fx_nominal = 1053.044591
    K_nominal = torch.zeros(C, 3, 3, device=device)
    K_nominal[:, 0, 0] = fx_nominal
    K_nominal[:, 1, 1] = fx_nominal
    K_nominal[:, 0, 2] = 960.0
    K_nominal[:, 1, 2] = 540.0
    K_nominal[:, 2, 2] = 1.0

    zoom_t = torch.full((1, C), zoom_cmd_value, device=device)
    Sigma_K = compute_sigma_K_from_zoom(zoom_t)
    sigma_fx = Sigma_K[0, 0, 0, 0].sqrt().item()
    sigma_fy = Sigma_K[0, 0, 1, 1].sqrt().item()
    sigma_cx = Sigma_K[0, 0, 2, 2].sqrt().item()
    sigma_cy = Sigma_K[0, 0, 3, 3].sqrt().item()

    N = n_samples
    K_pert = K_nominal.unsqueeze(0).expand(N, C, 3, 3).clone()
    K_pert[..., 0, 0] += torch.randn(N, C, device=device) * sigma_fx
    K_pert[..., 1, 1] += torch.randn(N, C, device=device) * sigma_fy
    K_pert[..., 0, 2] += torch.randn(N, C, device=device) * sigma_cx
    K_pert[..., 1, 2] += torch.randn(N, C, device=device) * sigma_cy

    cam_pos_b = cam_pos_nom.unsqueeze(0).expand(N, C, 3)
    cam_quat_b = cam_quat_nom.unsqueeze(0).expand(N, C, 4)
    R_wc, _, _, _, _ = build_camera_transforms(
        cam_pos_b, cam_quat_b,
        gimbal_zero.expand(N, C), gimbal_zero.expand(N, C), gimbal_zero.expand(N, C),
    )
    pixels, depth = project_through_intrinsics(X_target, cam_pos_b, R_wc, K_pert)

    T = 1
    bbox = torch.zeros(N, C, T, 4, device=device)
    bbox[:, :, 0, 0] = pixels[:, :, 0]
    bbox[:, :, 0, 1] = pixels[:, :, 1]
    bbox[:, :, 0, 2] = 50.0
    bbox[:, :, 0, 3] = 50.0
    bbox_valid = (depth > 1e-3).unsqueeze(-1)

    cfg = TriangulationCfg(
        pix_std=1e-3,
        include_pose_uncertainty=False,
        include_gimbal_uncertainty=False,
        include_intrinsics_uncertainty=True,
        intrinsics_std=1.0,
        condition_threshold=1e10,
        min_cameras_required=2,
    )
    K_nom_b = K_nominal.unsqueeze(0).expand(N, C, 3, 3)
    ray_dirs, _ = get_ray_directions_from_bbox(
        bbox, K_nom_b, cam_pos_b, cam_quat_b,
        gimbal_zero.expand(N, C), gimbal_zero.expand(N, C), gimbal_zero.expand(N, C),
    )
    X_tri, tri_valid, _, _ = triangulate_targets(cam_pos_b, ray_dirs, bbox_valid, cfg)

    samples = X_tri[tri_valid[:, 0], 0, :]

    # Analytical covariance at nominal scenario
    valid_mask = torch.ones(1, C, T, dtype=torch.bool, device=device)
    tri_valid_one = torch.ones(1, T, dtype=torch.bool, device=device)
    Sigma_X_an, _, is_valid_an = compute_triangulation_covariance(
        X_target=X_target.view(1, 1, 3),
        robot_positions=cam_pos_nom.unsqueeze(0),
        robot_quats=cam_quat_nom.unsqueeze(0),
        gimbal_yaws=gimbal_zero, gimbal_rolls=gimbal_zero, gimbal_pitches=gimbal_zero,
        camera_intrinsics=K_nominal.unsqueeze(0),
        valid_mask=valid_mask,
        triangulation_valid=tri_valid_one,
        cfg=cfg,
        Sigma_K_per_camera=Sigma_K,
    )
    if not is_valid_an[0, 0]:
        raise RuntimeError("Analytical covariance returned invalid")
    return samples, Sigma_X_an[0, 0], X_target, dict(
        sigma_fx=sigma_fx, sigma_fy=sigma_fy, sigma_cx=sigma_cx, sigma_cy=sigma_cy,
    )


# --------------------------- Plotting helpers ---------------------------

def add_cov_ellipse(ax, mean_2d, cov_2d, k_sigma, edgecolor, label=None):
    """Draw a 2D covariance ellipse at k·σ from mean."""
    vals, vecs = np.linalg.eigh(cov_2d)
    order = vals.argsort()[::-1]
    vals = vals[order]; vecs = vecs[:, order]
    angle = math.degrees(math.atan2(vecs[1, 0], vecs[0, 0]))
    width, height = 2 * k_sigma * np.sqrt(np.maximum(vals, 0.0))
    e = Ellipse(xy=mean_2d, width=width, height=height, angle=angle,
                fill=False, edgecolor=edgecolor, lw=2.0, label=label)
    ax.add_patch(e)


def plot_projections(samples_np, Sigma_an_np, target_np, save_path):
    """3 subplots: XY, XZ, YZ projections with MC scatter + analytic 1σ/2σ/3σ ellipses."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    pairs = [(0, 1, "X [m]", "Y [m]", "X-Y"),
             (0, 2, "X [m]", "Z [m]", "X-Z"),
             (1, 2, "Y [m]", "Z [m]", "Y-Z")]
    emp_mean = samples_np.mean(axis=0)
    centered = samples_np - emp_mean
    Sigma_emp = (centered.T @ centered) / centered.shape[0]
    for ax, (a, b, xl, yl, ttl) in zip(axes, pairs):
        ax.scatter(samples_np[:, a], samples_np[:, b], s=2, alpha=0.25,
                   color="#3b82f6", label=f"MC samples (n={samples_np.shape[0]})")
        ax.scatter([target_np[a]], [target_np[b]], color="black", marker="x", s=80,
                   label="ground truth", zorder=5)
        # Analytical ellipses centered at GT
        cov_an_2d = Sigma_an_np[np.ix_([a, b], [a, b])]
        for k, ec, lab in [(1, "#ef4444", "Analytic 1σ"),
                           (2, "#dc2626", "Analytic 2σ"),
                           (3, "#991b1b", "Analytic 3σ")]:
            add_cov_ellipse(ax, (target_np[a], target_np[b]), cov_an_2d, k, ec, label=lab)
        # Empirical 2σ ellipse for direct comparison
        cov_em_2d = Sigma_emp[np.ix_([a, b], [a, b])]
        add_cov_ellipse(ax, (emp_mean[a], emp_mean[b]), cov_em_2d, 2, "#16a34a",
                        label="Empirical 2σ")
        ax.set_xlabel(xl); ax.set_ylabel(yl); ax.set_title(ttl)
        ax.set_aspect("equal", adjustable="datalim")
        ax.grid(alpha=0.3)
        if a == 0 and b == 1:
            ax.legend(loc="upper right", fontsize=8)
    fig.suptitle("Triangulation covariance — MC samples vs analytic ellipses",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_marginals(samples_np, Sigma_an_np, target_np, save_path):
    """Per-axis MC histogram with analytical Gaussian PDF (centered at GT)."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    labels = ["X [m]", "Y [m]", "Z [m]"]
    emp_mean = samples_np.mean(axis=0)
    emp_std = samples_np.std(axis=0)
    for i, ax in enumerate(axes):
        sigma_an = math.sqrt(max(Sigma_an_np[i, i], 0.0))
        # histogram in residual space (sample - GT)
        x = samples_np[:, i] - target_np[i]
        ax.hist(x, bins=60, density=True, color="#3b82f6", alpha=0.55,
                edgecolor="white", label="MC")
        xs = np.linspace(x.min(), x.max(), 400)
        if sigma_an > 0:
            pdf_an = np.exp(-0.5 * (xs / sigma_an) ** 2) / (sigma_an * math.sqrt(2 * math.pi))
            ax.plot(xs, pdf_an, color="#ef4444", lw=2.2,
                    label=f"Analytic N(0, {sigma_an:.3f}²)")
        ax.axvline(emp_mean[i] - target_np[i], color="#16a34a", lw=1.2, ls="--",
                   label=f"Empirical μ ({emp_mean[i] - target_np[i]:+.3f})")
        ax.set_xlabel(labels[i] + " residual")
        ax.set_ylabel("density")
        ax.set_title(f"{labels[i]}: σ_emp={emp_std[i]:.3f}, σ_an={sigma_an:.3f}")
        ax.grid(alpha=0.3)
        ax.legend(fontsize=9)
    fig.suptitle("Marginal residual distributions vs analytic Gaussian",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_nees(samples_np, Sigma_an_np, target_np, save_path):
    """Mahalanobis² (NEES) histogram vs χ²(3) PDF + cumulative coverage."""
    delta = samples_np - target_np
    try:
        Sigma_inv = np.linalg.inv(Sigma_an_np)
    except np.linalg.LinAlgError:
        Sigma_inv = np.linalg.pinv(Sigma_an_np)
    nees = np.einsum("ni,ij,nj->n", delta, Sigma_inv, delta)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Left: histogram vs chi2(3) PDF
    ax = axes[0]
    xmax = float(np.percentile(nees, 99.5))
    ax.hist(nees, bins=80, range=(0, xmax), density=True, color="#3b82f6",
            alpha=0.55, edgecolor="white", label=f"MC NEES (n={len(nees)})")
    xs = np.linspace(1e-4, xmax, 400)
    if HAS_SCIPY:
        ax.plot(xs, chi2_dist.pdf(xs, df=3), color="#ef4444", lw=2.2,
                label="χ²(3) PDF (analytic)")
    else:
        # Fallback chi-square pdf
        pdf = (xs ** 0.5) * np.exp(-xs / 2.0) / (math.sqrt(2 * math.pi))
        ax.plot(xs, pdf, color="#ef4444", lw=2.2, label="χ²(3) PDF")
    ax.set_xlabel("NEES = δᵀ Σ⁻¹ δ")
    ax.set_ylabel("density")
    ax.set_title(f"NEES distribution (mean={nees.mean():.2f}, expected=3.0)")
    ax.grid(alpha=0.3); ax.legend(fontsize=9)

    # Right: empirical vs theoretical cumulative coverage
    # P(NEES <= k²) under H0 is the χ²(3) CDF — compare empirical mass to it.
    ax = axes[1]
    ks = np.linspace(0.25, 3.5, 30)
    thresholds = ks ** 2
    emp_cov = np.array([(nees <= t).mean() for t in thresholds])
    if HAS_SCIPY:
        ana_cov = chi2_dist.cdf(thresholds, df=3)
        ax.plot(ks, ana_cov, color="#ef4444", lw=2.2, label="Analytic χ²(3) CDF")
    ax.plot(ks, emp_cov, "o-", color="#3b82f6", lw=1.8, label="Empirical coverage")
    ax.set_xlabel("ellipsoid radius k (NEES ≤ k²)")
    ax.set_ylabel("P(NEES ≤ k²)")
    ax.set_title("Cumulative ellipsoid coverage")
    ax.set_ylim(0, 1.05); ax.grid(alpha=0.3); ax.legend(fontsize=9)

    fig.suptitle("Whiteness check — analytical Σ should make MC NEES ~ χ²(3)",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return nees


def plot_zoom_sweep(zoom_cmds, traces_an, traces_em, traces_em_se, save_path):
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(zoom_cmds, traces_an, "s--", color="#ef4444", lw=2.0, ms=10,
            label="Analytic trace(Σ_X)")
    ax.errorbar(zoom_cmds, traces_em, yerr=traces_em_se, fmt="o-", color="#3b82f6",
                lw=2.0, ms=8, capsize=5, label="MC trace(Σ_X) ±SE")
    ax.set_xlabel("zoom command (1x .. 5x)")
    ax.set_ylabel("trace(Σ_X) [m²]")
    ax.set_title("Triangulation covariance scaling with zoom — analytic vs MC")
    ax.set_yscale("log")
    ax.grid(alpha=0.3, which="both"); ax.legend(fontsize=10)
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_matrix_compare(samples_np, Sigma_an_np, save_path):
    """Side-by-side heatmap of empirical Σ vs analytical Σ + relative error."""
    centered = samples_np - samples_np.mean(axis=0)
    Sigma_em = (centered.T @ centered) / centered.shape[0]

    # Normalize the absolute error by trace(Σ_an) so off-diagonal near-zero
    # entries don't explode when divided element-wise.
    trace_an = max(float(np.trace(Sigma_an_np)), 1e-12)
    err_norm = np.abs(Sigma_em - Sigma_an_np) / trace_an

    fig, axes = plt.subplots(1, 3, figsize=(18, 5.5))
    vmax = max(np.abs(Sigma_em).max(), np.abs(Sigma_an_np).max())
    for ax, M, ttl in zip(
        axes[:2],
        [Sigma_em, Sigma_an_np],
        ["Empirical Σ_X (MC)", "Analytic Σ_X"],
    ):
        im = ax.imshow(M, cmap="RdBu_r", vmin=-vmax, vmax=vmax)
        ax.set_xticks([0, 1, 2]); ax.set_xticklabels(["X", "Y", "Z"])
        ax.set_yticks([0, 1, 2]); ax.set_yticklabels(["X", "Y", "Z"])
        ax.set_title(f"{ttl}\ntrace = {np.trace(M):.4f} m²")
        for i in range(3):
            for j in range(3):
                ax.text(j, i, f"{M[i, j]:.4f}", ha="center", va="center",
                        color="black", fontsize=10)
        plt.colorbar(im, ax=ax, fraction=0.046)

    ax = axes[2]
    im = ax.imshow(err_norm, cmap="viridis", vmin=0,
                   vmax=max(err_norm.max(), 1e-3))
    ax.set_xticks([0, 1, 2]); ax.set_xticklabels(["X", "Y", "Z"])
    ax.set_yticks([0, 1, 2]); ax.set_yticklabels(["X", "Y", "Z"])
    ax.set_title("|Σ_emp − Σ_an| / trace(Σ_an)")
    for i in range(3):
        for j in range(3):
            ax.text(j, i, f"{err_norm[i, j]:.4f}", ha="center", va="center",
                    color="white", fontsize=10)
    plt.colorbar(im, ax=ax, fraction=0.046)

    fig.suptitle("Covariance matrix comparison (3×3)",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# --------------------------- main ---------------------------

def main() -> int:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(args_cli.seed)
    np.random.seed(args_cli.seed)

    if args_cli.save_dir is not None:
        out_dir = args_cli.save_dir
    else:
        out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "mc_plots", "intrinsic_cov")
    os.makedirs(out_dir, exist_ok=True)

    print("=" * 80)
    print("Plot: triangulation Σ_X (MC vs analytic, intrinsic block)")
    print("=" * 80)
    print(f"Device:           {device}")
    print(f"N samples:        {args_cli.n_samples}")
    print(f"Zoom (headline):  {args_cli.zoom_cmd}")
    print(f"Target distance:  {args_cli.target_distance} m")
    print(f"Output dir:       {out_dir}")

    # ---- headline scenario ----
    samples, Sigma_an, X_target, sigmas = run_mc(
        args_cli.zoom_cmd, args_cli.target_distance, args_cli.n_samples, device,
    )
    print(f"Valid MC samples: {samples.shape[0]} / {args_cli.n_samples}")
    print("σ_fx={sigma_fx:.2f}, σ_fy={sigma_fy:.2f}, σ_cx={sigma_cx:.2f}, σ_cy={sigma_cy:.2f} px"
          .format(**sigmas))

    samples_np = samples.cpu().numpy()
    Sigma_an_np = Sigma_an.cpu().numpy()
    target_np = X_target.cpu().numpy()

    plot_projections(samples_np, Sigma_an_np, target_np,
                     os.path.join(out_dir, "cov_projections.png"))
    plot_marginals(samples_np, Sigma_an_np, target_np,
                   os.path.join(out_dir, "marginal_histograms.png"))
    nees = plot_nees(samples_np, Sigma_an_np, target_np,
                     os.path.join(out_dir, "nees_chi2.png"))
    plot_matrix_compare(samples_np, Sigma_an_np,
                        os.path.join(out_dir, "matrix_compare.png"))

    print(f"NEES mean: {nees.mean():.3f}  (expected 3.0)")
    print(f"NEES median: {np.median(nees):.3f}")

    # ---- zoom sweep ----
    sweep = [float(z) for z in args_cli.zoom_sweep.split(",") if z.strip()]
    traces_an, traces_em, traces_em_se = [], [], []
    sweep_n = max(args_cli.n_samples // 2, 2000)
    print(f"\nZoom sweep (n={sweep_n} per point): {sweep}")
    for z in sweep:
        s, Sx, _, _ = run_mc(z, args_cli.target_distance, sweep_n, device)
        s_np = s.cpu().numpy()
        c = s_np - s_np.mean(axis=0)
        Sigma_em = (c.T @ c) / c.shape[0]
        tr_em = float(np.trace(Sigma_em))
        tr_an = float(torch.trace(Sx).item())
        # rough SE: independent contributions ~ 2/(n) * trace²
        se_em = tr_em * math.sqrt(2.0 / max(c.shape[0], 1))
        traces_em.append(tr_em); traces_em_se.append(se_em); traces_an.append(tr_an)
        print(f"  z={z:.1f}  trace_an={tr_an:.4f}  trace_em={tr_em:.4f}  "
              f"rel_err={abs(tr_an - tr_em) / max(tr_em, 1e-12) * 100:.1f}%")

    plot_zoom_sweep(sweep, traces_an, traces_em, traces_em_se,
                    os.path.join(out_dir, "zoom_sweep.png"))

    print("\nWrote:")
    for f in ["cov_projections.png", "marginal_histograms.png", "nees_chi2.png",
              "matrix_compare.png", "zoom_sweep.png"]:
        p = os.path.join(out_dir, f)
        ok = "✓" if os.path.exists(p) else "✗"
        print(f"  {ok} {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
